name: Keep Render Awake

on:
  schedule:
    - cron: "*/15 * * * *"  # executa a cada 15 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render
        run: curl -I https://jl-site.onrender.com/#inicio
